wandb/yea-wandb

.gitignore, setup.py, src/yea_wandb/mock_server.py, src/yea_wandb/plugin.py, tests/plugin_test.py
- removes old yea "check" code (we should use "assert" now)
- adds mock_server multirun for run and filestream (not files or artifacts or many other things)
- Fixes config dict issue
=> yea-wandb 0.4.1

src/yea_wandb/plugin.py, tests/configs/contains-regex-test.yea, tests/configs/count-regex-test.yea, tests/plugin_test.py
2 ops: `contains_regex` and `not_contains_regex`
1 fn: `count_regex`
=> added two functions with regex matching: contains and count

src/yea_wandb/artifact_emu.py, src/yea_wandb/mock_server.py, src/yea_wandb/plugin.py
Adds a new function, `fn_sum`, that reduces a list to the sum of its elements. Used to calculate the number of gradient values logged in the docstring functional test `init-and-log-histogram`  in https://github.com/wandb/client/pull/2846/commits/646fd7f2374085cd38d48088f8b3df133a1c98cb.
=> Add fn_sum

src/yea_wandb/mock_server.py
This PR adds the logic to mock server that is necessary for supporting this test in yeadoc:
https://github.com/wandb/client/pull/2846/files#diff-459010419144595553131450d029320d8a44630ac6fe8ce344f8bcc49c18b87a
Since this needs to be a part of yea before the client PR can be green, I am opening this PR first and requesting review from @raubitsj. Once this update to the mock server gets approved I will release yea-wandb, copy these changes over to the client PR to maintain sync, then pin the pr to the newly releaseed yea-wandb version so that the newly introduced functional tests pass there
=> add logic for yeadoc sweep controller test to mock server

src/yea_wandb/mock_requests.py, src/yea_wandb/mock_server.py
Tested with client:
https://github.com/wandb/client/pull/3138
=> Sync with client 0.12.9

src/yea_wandb/backend.py, src/yea_wandb/mock_server.py, src/yea_wandb/plugin.py
The linked wandb/client change is at:
https://github.com/wandb/client/pull/3226
=> Add sentry support to yea!

.bumpversion.cfg, Makefile, setup.cfg, setup.py, src/yea_wandb/__init__.py, tools/bumpversion-tool.py
Mostly lifted from @dannygoldstein's stuff in `wandb/sweeps`, but uses a maintained fork of `bumpversion`.
=> Bump version tooling + pin latest yea

pyproject.toml, src/yea_wandb/artifact_emu.py, src/yea_wandb/backend.py, src/yea_wandb/plugin.py
=> black formatting to make syncing work on the client

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/mock_server.py
+ bump version
(see https://github.com/wandb/client/pull/3718)
=> Bring in the change from `wandb/client#3718`

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/mock_server.py
=> test(sdk): Add mocks for report editing

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/mock_server.py
Sync with the changes in this PR: https://github.com/wandb/client/pull/3706
=> add new mock server fields for server hints

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/mock_server.py
See:
https://github.com/wandb/client/pull/3933
=> Mockserver fix filestream

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/plugin.py
Required by this PR:
https://github.com/wandb/yea/pull/36
The above PR needs to be merged first as they are coupled.  API change in the test_check plugin interface.
=> yea-wandb: 0.8.10 - Add ResultData structure to enable perf report

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/mock_server.py
This is the yea mock changes supporting https://github.com/wandb/wandb/pull/4531
=> fix(public-api): Changed artifactSequence to artifactCollection in public GQL requests

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/mock_server.py
fix(artifacts): add s3 multipart uploading for artifact files
https://github.com/wandb/wandb/pull/5377
=> yea-wandb 0.9.8 multipart upload mock_server.py changes

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/mock_server.py
=> Revert "Sync from wandb PR #5534"

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/mock_server.py
Syncing changes from https://github.com/wandb/wandb/pull/5454
=> Sync from wandb PR #5454

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/mock_server.py
Syncing changes from https://github.com/wandb/wandb/pull/5692
=> Sync from wandb PR #5692

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/mock_server.py
=> Sync from wandb PR #5810

.bumpversion.cfg, setup.py, src/yea_wandb/__init__.py, src/yea_wandb/mock_server.py
See https://github.com/wandb/wandb/pull/5893
=> Add ProbeServerCreateLaunchAgentInput query
